export default {
  count: 1348,
  next: 'http://localhost:8000/api/v1/ramps/token/pol/?page=2',
  previous: null,
  results: [
    {
      id: 33065,
      name: 'MetaTrace Utility Token',
      symbol: 'ACE',
      key: 'ACE',
      address: '0x9627a3d6872bE48410fCEce9b1dDD344Bf08c53e',
      decimals: 2,
      is_onramp_verified: true,
      is_offramp_verified: true,
      is_onramp_active: false,
      is_offramp_active: false,
      image_url: null,
      min_allowance: null,
      max_allowance: null,
    },
    {
      id: 33000,
      name: 'Krasnalcoin',
      symbol: 'KC',
      key: 'KC',
      address: '0x784665471bB8B945b57A76a9200B109Ee214E789',
      decimals: 6,
      is_onramp_verified: true,
      is_offramp_verified: true,
      is_onramp_active: false,
      is_offramp_active: false,
      image_url: null,
      min_allowance: null,
      max_allowance: null,
    },
    {
      id: 33410,
      name: 'Medieus Token',
      symbol: 'MDUS',
      key: 'MDUS',
      address: '0xAb9CB20A28f97e189ca0B666B8087803Ad636b3C',
      decimals: 18,
      is_onramp_verified: true,
      is_offramp_verified: true,
      is_onramp_active: false,
      is_offramp_active: false,
      image_url: null,
      min_allowance: null,
      max_allowance: null,
    },
  ],
};
